### ISSUE TITLE
求助，fabric1.0 没有client等证书，所以只配置了server.crt。验证通道时报错

### ISSUE THREAD

**Issue by mccok** [aberic/fabric-net-server#39]
请求接口：http://localhost:port/state/invoke

请求方式：POST

请求参数：{"flag":"b51ff3882a10718a","strArray":["invoke","a","b","2"],"key":"8i1UgBrq"}

请求结果：{"code":9999,"error":"Request failed： null"}

查看后台日志：
在录入通道时显示如下日志：（求助是什么原因）

07:04:59.090 INFO  cn.aberic.fabric.sdk.IntermediateUser 291 getKeyForFabricStoreName - toKeyValStoreName = user.amicoOrg1MSPpeer0.org1.example.comAdmin
edge    | 07:04:59.090 INFO  cn.aberic.fabric.sdk.IntermediateUser 291 getKeyForFabricStoreName - toKeyValStoreName = user.amicoOrg1MSPpeer0.org1.example.comAdmin
edge    | 07:04:59.090 INFO  cn.aberic.fabric.sdk.IntermediateUser 291 getKeyForFabricStoreName - toKeyValStoreName = user.amicoOrg1MSPpeer0.org1.example.comAdmin
edge    | 07:04:59.093 INFO  cn.aberic.fabric.sdk.IntermediateUser 291 getKeyForFabricStoreName - toKeyValStoreName = user.amicoOrg1MSPpeer0.org1.example.comAdmin
edge    | 07:04:59.093 INFO  cn.aberic.fabric.sdk.IntermediateOrg 183 setClient - Create instance of HFClient
edge    | 07:04:59.093 INFO  cn.aberic.fabric.sdk.IntermediateOrg 185 setClient - Set Crypto Suite of HFClient
edge    | 07:04:59.093 INFO  cn.aberic.fabric.sdk.IntermediateChannel 71 setChannel - Get Chain mychannel
edge    | 07:04:59.094 WARN  cn.aberic.fabric.service.impl.TraceServiceImpl 137 trace - Request failed? null

**Comment by mccok** [comment]
###1.0-RC6在升级链码时报如下的错误：（求助该如何解决 @aberic  @AbericYang @lipengfei217   ），尝试了好多遍，还是一样。而且前端页面上该升级的链码也显示不见了

05:58:24.486 DEBUG cn.aberic.fabric.utils.FabricHelper 103 get - org = Org(id=1, name=Org1, tls=true, mspId=Org1MSP, leagueId=1, leagueName=null, date=2018-12-27, peerCount=0, ordererCount=0)
java.lang.NullPointerException
	at cn.aberic.fabric.utils.FabricHelper.get(FabricHelper.java:112)
	at cn.aberic.fabric.service.impl.ChaincodeServiceImpl.chainCode(ChaincodeServiceImpl.java:189)
	at cn.aberic.fabric.service.impl.ChaincodeServiceImpl.upgrade(ChaincodeServiceImpl.java:109)
	at cn.aberic.fabric.controller.ChaincodeController.submit(ChaincodeController.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:877)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
05:58:24.488 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - ==>  Preparing: delete from app where chaincode_id=? 
05:58:24.489 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - ==> Parameters: 4(Integer)
05:58:24.603 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - <==    Updates: 1

**Comment by Ruben-Joseph-Halder** [comment]
解决了吗

**Comment by susengo** [comment]
这问题怎么解决啊，总是连不上fabric，也不知道从哪儿排查
