### ISSUE TITLE
HyperLedger Fabric网络交互  配置通道完,点击首页日志报错,报错如下

### ISSUE THREAD

**Issue by 18001836048** [aberic/fabric-net-server#45]
Caused by: org.hyperledger.fabric.sdk.exception.ProposalException: getConfigBlock for channel mychannel failed with peer foo27.org2.example.com.  Status FAILURE, details: Sending proposal to foo27.org2.example.com failed because of: gRPC failure=Status{code=UNKNOWN, description=access denied: channel [mychannel] creator org [Org2MSP], cause=null}
edge    | 	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:786)
edge    | 	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1187)
edge    | 	... 67 more
edge    | 09:21:08.538 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - ==>  Preparing: select rowid,name,location,event_hub_location,server_crt_path,org_id,date from peer where rowid=? 
edge    | 09:21:08.538 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - ==> Parameters: 1(Integer)
edge    | 09:21:08.538 DEBUG org.apache.ibatis.logging.jdbc.BaseJdbcLogger 159 debug - <==      Total: 1
edge    | java.lang.NullPointerException
edge    | 	at cn.aberic.fabric.controller.CommonController.index(CommonController.java:105)
edge    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
edge    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
edge    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
edge    | 	at java.lang.reflect.Method.invoke(Method.java:498)
edge    | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
edge    | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
edge    | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
edge    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:877)
edge    | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:783)
edge    | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
edge    | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
edge    | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
edge    | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
edge    | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:866)
edge    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
edge    | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
edge    | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
edge    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)
edge    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
edge    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
edge    | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
edge    | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
edge    | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
edge    | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
edge    | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
edge    | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
edge    | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
edge    | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
edge    | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
edge    | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
edge    | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
edge    | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
edge    | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1468)
edge    | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
edge    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
edge    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
edge    | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
edge    | 	at java.lang.Thread.run(Thread.java:748)

**Comment by 18001836048** [comment]
谁能解答一下

**Comment by Ruben-Joseph-Halder** [comment]
解决了吗

**Comment by joey1212** [comment]
ca配置的CA sk文件在“peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/”
CA Certificate的文件在
“peerOrganizations/org1.example.com/ca/ca.org1.example.com-cert.pem”
